server:
  port: 9090
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://cmxtykadeyihsr:55194348f0e6747183f2c8dc9cd865d75d6e5874ac7fedf8e446a46259c5e412@ec2-3-215-57-87.compute-1.amazonaws.com:5432/de1hmg95vuic2f
    username: cmxtykadeyihsr
    password: 55194348f0e6747183f2c8dc9cd865d75d6e5874ac7fedf8e446a46259c5e412
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto Criado por FernandOlle para bootcamp DIO - Santander
  version: 0.9.0
